CC := gcc
FLEX := flex
BISON := bison

CFLAGS := -Wall -Wextra -Ibuild
BUILD_DIR := build

LEXER_SOURCE := lexer/lexer.l
LEXER_GENERATED := $(BUILD_DIR)/lex.yy.c

PARSER_SOURCE := parser/parser.y
PARSER_GENERATED_C := $(BUILD_DIR)/parser.tab.c
PARSER_GENERATED_H := $(BUILD_DIR)/parser.tab.h
PARSER_BINARY := $(BUILD_DIR)/parser

.PHONY: all parser clean

all: parser

parser: $(PARSER_BINARY)

$(PARSER_BINARY): $(PARSER_GENERATED_C) $(PARSER_GENERATED_H) $(LEXER_GENERATED) | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(PARSER_GENERATED_C) $(LEXER_GENERATED) -o $@

$(PARSER_GENERATED_C) $(PARSER_GENERATED_H): $(PARSER_SOURCE) | $(BUILD_DIR)
	$(BISON) -d -o $(PARSER_GENERATED_C) $(PARSER_SOURCE)

$(LEXER_GENERATED): $(LEXER_SOURCE) $(PARSER_GENERATED_H) | $(BUILD_DIR)
	$(FLEX) -o $(LEXER_GENERATED) $(LEXER_SOURCE)

$(BUILD_DIR):
	mkdir -p $@

clean:
	rm -rf $(BUILD_DIR)